Dr 125
MyWishPlatform/mywill_scanner pull request #24
Opened 2021-12-27 15:12 UTC by reloverevolt

2021-12-28 10:44 UTC, yulian-khalitov requested changes

2021-12-28 10:44 UTC, qwdqwqdwqd commented on monitors/payments/btc.py
> +        if self.network_type.split('_')[1] == 'MAINNET':
`ntype = 'mainnet' if 'MAINNET' in self.network_type else 'testnet'`

2021-12-28 10:44 UTC, qwdqwqdwqd commented on monitors/payments/btc.py
> +        return first_input['address']
```
try:
  return res.json()['inputs'][0]['address']
except KeyError, IndexError:
  return None
```

2021-12-28 10:44 UTC, yulian-khalitov commented on monitors/payments/btc.py
> +                        'fromAddress': self.get_sent_from_address(transaction.tx_hash),
кхе-кхе
https://bitcoin.stackexchange.com/questions/89207/how-to-get-input-address-and-amount-from-vin-using-bitcoin-core-rpc

2021-12-28 11:25 UTC, reloverevolt commented on monitors/payments/btc.py
> +        if self.network_type.split('_')[1] == 'MAINNET':
ну вот эта штука получается не нужна так как в конфигас сети могу тест нет прописать

2021-12-28 12:55 UTC, reloverevolt commented on monitors/payments/btc.py
> +        return first_input['address']
кайф

2021-12-28 12:55 UTC, reloverevolt commented on monitors/payments/btc.py
> +        return first_input['address']
кайф

2021-12-29 13:03 UTC, yulian-khalitov requested changes

2021-12-29 13:03 UTC, qwdqwqdwqd commented on settings/config.example.yaml
> +    tx_status_url: 'https://api.bitcore.io/api/BTC/testnet/tx/{tx_hash}/coins'
может лучше только `bitcore_url: https://api.bitcore.io/api/BTC/testnet/` оставить? а в бэке уже дописывать урл в зависимости от того что нужно

а то как-то вставлять f-string в конфиг стрём

2021-12-29 13:09 UTC, reloverevolt commented on settings/config.example.yaml
> +    tx_status_url: 'https://api.bitcore.io/api/BTC/testnet/tx/{tx_hash}/coins'
ok, не вопрос

2021-12-29 13:26 UTC, yulian-khalitov requested changes

2021-12-29 13:26 UTC, yulian-khalitov commented on monitors/payments/btc.py
> +    tx_status_url: str
=(

2021-12-29 13:26 UTC, yulian-khalitov commented on monitors/payments/btc.py
> +        if not bitcore_url:
=((

2021-12-29 13:49 UTC, yulian-khalitov approved these changes

2021-12-29 13:50 UTC, merged